<div class="recom">
    <div class="block-title">
        <strong><span>热销推荐</span></strong>
    </div>
    <div class="btndiv">
        <a class="aleft" href="#left"></a>
        <a class="aright" href="#right"></a>
    </div>
    <div class="scrollcontainer" >
        <ul>
            <li>
                <a href="/1118894.html">
                    <p class="plmg"><img src="{{media url="wysiwyg/slides/antipodes.png"}}" alt="" /></p>
                    <p>Antipodes 奇异果籽油滋养修复眼霜 30ml</p>
                    <p class="price">NZD $42.5</p>
                </a>
            </li>
            <li>
                <a href="/1123955.html">
                    <p class="pImg"><img src="{{media url="wysiwyg/slides/trilogy.png"}}" alt="" /></p>
                    <p>Trilogy 趣乐活 玫瑰果油 20ml</p>
                    <p class="price">NZD $18.45</p>
                </a>
            </li>
            <li>
                <a href="/1119853.html">
                    <p class="pImg"><img src="{{media url="wysiwyg/slideshotsales/honey.jpg"}}" alt="" /></p>
                    <p>Comvita 康维他 麦卢卡蜂蜜 UMF5+ 250g</p>
                    <p class="price">NZD $32.9</p>
                </a>
            </li>
            <li>
                <a href="/1119353.html">
                    <p class="pImg"><img src="{{media url="wysiwyg/slideshotsales/bmfoc.jpg"}}" alt="" /></p>
                    <p>Blackmores 澳佳宝 深海鱼油迷你胶囊 400粒</p>
                    <p class="price">NZD $31.5</p>
                </a>
            </li>
            <li>
                <a href="/1123698.html">
                    <p class="pImg"><img src="{{media url="wysiwyg/slideshotsales/swisse.jpg"}}" alt="" /></p>
                    <p>Swisse 薄荷味叶绿素(排毒养颜）500ml</p>
                    <p class="price">NZD $24.2</p>
                </a>
            </li>
        </ul>
    </div>
</div>

<script>

    (function(jQuery){
        jQuery.extend(jQuery.easing,{
            easeInSine: function (x, t, b, c, d) {
                return -c * Math.cos(t/d * (Math.PI/2)) + c + b;
            }
        });

        jQuery.fn.Xslider=function(settings){
            settings=jQuery.extend({},jQuery.fn.Xslider.sn.defaults,settings);
            this.each(function(){
                var scrollobj=settings.scrollobj ? jQuery(this).find(settings.scrollobj) : jQuery(this).find("ul"),
                    viewedSize=settings.viewedSize || (settings.dir=="H" ? scrollobj.parent().width() : scrollobj.parent().height()),//length of the wrapper visible;
                    scrollunits=scrollobj.find("li"),//units to move;
                    unitlen=settings.unitlen || (settings.dir=="H" ? scrollunits.eq(0).outerWidth() : scrollunits.eq(0).outerHeight()),
                    unitdisplayed=settings.unitdisplayed,//units num displayed;
                    numtoMove=settings.numtoMove > unitdisplayed ? unitdisplayed : settings.numtoMove,
                    scrollobjSize=settings.scrollobjSize || scrollunits.length*unitlen,//length of the scrollobj;
                    offset=0,//max width to move;
                    offsetnow=0,//scrollobj now offset;
                    movelength=unitlen*numtoMove,
                    pos=settings.dir=="H" ? "left" : "top",
                    moving=false,//moving now?;
                    btnright=jQuery(this).find("a.aright"),
                    btnleft=jQuery(this).find("a.aleft");

                btnright.unbind("click");
                btnleft.unbind("click");

                settings.dir=="H" ? scrollobj.css("left","0px") : scrollobj.css("top","0px");

                if(scrollobjSize>viewedSize){
                    if(settings.loop=="cycle"){
                        btnleft.removeClass("agrayleft");
                        if(scrollunits.length<2*numtoMove+unitdisplayed-numtoMove){
                            scrollobj.find("li").clone().appendTo(scrollobj);
                        }
                    }else{
                        btnleft.addClass("agrayleft");
                        offset=scrollobjSize-viewedSize;
                    }
                    btnright.removeClass("agrayright");
                }else{
                    btnleft.addClass("agrayleft");
                    btnright.addClass("agrayright");
                }

                btnleft.click(function(){
                    if(jQuery(this).is("[class*='agrayleft']")){return false;}

                    if(!moving){
                        moving=true;

                        if(settings.loop=="cycle"){
                            scrollobj.find("li:gt("+(scrollunits.length-numtoMove-1)+")").prependTo(scrollobj);
                            scrollobj.css(pos,"-"+movelength+"px");
                            jQuery.fn.Xslider.sn.animate(scrollobj,0,settings.dir,settings.speed,function(){moving=false;});
                        }else{
                            offsetnow-=movelength;
                            if(offsetnow>unitlen*unitdisplayed-viewedSize){
                                jQuery.fn.Xslider.sn.animate(scrollobj,-offsetnow,settings.dir,settings.speed,function(){moving=false;});
                            }else{
                                jQuery.fn.Xslider.sn.animate(scrollobj,0,settings.dir,settings.speed,function(){moving=false;});
                                offsetnow=0;
                                jQuery(this).addClass("agrayleft");
                            }
                            btnright.removeClass("agrayright");
                        }
                    }

                    return false;
                });
                btnright.click(function(){
                    if(jQuery(this).is("[class*='agrayright']")){return false;}

                    if(!moving){
                        moving=true;

                        if(settings.loop=="cycle"){
                            var callback=function(){
                                scrollobj.find("li:lt("+numtoMove+")").appendTo(scrollobj);
                                scrollobj.css(pos,"0px");
                                moving=false;
                            }
                            jQuery.fn.Xslider.sn.animate(scrollobj,-movelength,settings.dir,settings.speed,callback);
                        }else{
                            offsetnow+=movelength;
                            if(offsetnow<offset-(unitlen*unitdisplayed-viewedSize)){
                                jQuery.fn.Xslider.sn.animate(scrollobj,-offsetnow,settings.dir,settings.speed,function(){moving=false;});
                            }else{
                                jQuery.fn.Xslider.sn.animate(scrollobj,-offset,settings.dir,settings.speed,function(){moving=false;});//滚动到最后一个位置;
                                offsetnow=offset;
                                jQuery(this).addClass("agrayright");
                            }
                            btnleft.removeClass("agrayleft");
                        }
                    }

                    return false;
                });

                if(settings.autoscroll){
                    jQuery.fn.Xslider.sn.autoscroll(jQuery(this),settings.autoscroll);
                }
            })
        }

        jQuery.fn.Xslider.sn={
            defaults:{
                dir:"H",
                speed:500
            },
            animate:function(obj,w,dir,speed,callback){
                if(dir=="H"){
                    obj.animate({
                        left:w
                    },speed,"easeInSine",callback);
                }else if(dir=="V"){
                    obj.animate({
                        top:w
                    },speed,"easeInSine",callback);
                }
            },
            autoscroll:function(obj,time){
                var  vane="right";
                function autoscrolling(){
                    if(vane=="right"){
                        if(!obj.find("a.agrayright").length){
                            obj.find("a.aright").trigger("click");
                        }else{
                            vane="left";
                        }
                    }
                    if(vane=="left"){
                        if(!obj.find("a.agrayleft").length){
                            obj.find("a.aleft").trigger("click");
                        }else{
                            vane="right";
                        }
                    }
                }
                var scrollTimmer=setInterval(autoscrolling,time);
                obj.hover(function(){
                    clearInterval(scrollTimmer);
                },function(){
                    scrollTimmer=setInterval(autoscrolling,time);
                });
            }
        }
    })(jQuery);

    jQuery(function(){
        jQuery(".recom").Xslider({
            unitdisplayed:1,
            numtoMove:1,
            speed:300,
            scrollobjSize:Math.ceil(jQuery(".recom").find("li").length/1)*180
        })
        jQuery(".recom").Xslider.sn.autoscroll(jQuery(".recom"),5000);
    });

</script>